Website/TechnicalCourses/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# URLs for the Technical Courses app
app_name = 'TechnicalCourses'
urlpatterns = [
    # path('', [name-of-function], name='[name-of-page])
    path('<int:course_id>/',views.detail, name='detail'),
    path('', views.Courses, name='home-page'),
    path('<int:course_id>/yourchoice/', views.yourchoice, name='yourchoice'),
]

Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TechnicalCourses.urls')),#include path of home-page
]

Website/TechnicalCourses/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.
class Allcourses(models.Model):
    # course name
    coursename = models.CharField(max_length=200)
    # instructor name
    insname = models.CharField(max_length=100)
    startedfrom = models.DateTimeField('Started from')

    # When defining a function inside a class,
    # we need to use the (self) parameter:
    # The below function will return the coursename instead of the object id
    def __str__(self):
        return self.coursename

    # datetime from django libary
    # timezone from django.utils
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.startedfrom <= now


class details(models.Model):
    # Each class that has been created here is a sub-class of the django.db.models.Model
    # ForeignKey connects this subclass to main class. ForeignKey defines a relationship.
    # Inherits Allcourse method
    # on_delete: in case we delete any course present in 'Allcourses',
    #           we want to delete the details of that function as well
    course = models.ForeignKey(Allcourses, on_delete=models.CASCADE)
    # ct = course type
    ct = models.CharField(max_length=500)
    # your_choice specifies option selected by user
    your_choice = models.BooleanField(default=False)
    # sp = self-paced course: used to specify the topics present in the course
    # sp = models.CharField(max_length=500)
    # il = instructor-led courses
    # il = models.CharField(max_length=500)

    # When defining a function inside a class,
    # we need to use the (self) parameter:
    def __str__(self):
        # Return the primary key of course
        return str(self.ct)

Website/TechnicalCourses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Allcourses
from django.template import loader


# Create your views here.
def Courses(request):
    # ac = all course
    ac = Allcourses.objects.all()
    template = loader.get_template('TechnicalCourses/Courses.html')
    # context is a dictionary-mapping template variable name to python objects
    context = {
        # store all the elements (e.g. courses) that are present
        'ac': ac,
    }
    return HttpResponse(template.render(context, request))


def detail(request,course_id):
    # This fetches the Allcourses object corresponding to course_id passed into detail()
    course = get_object_or_404(Allcourses, pk=course_id)
    # This returns the html page using the detail.html template with course (variable set above)
    # set passed as the 'course' parameter in the html file
    return render(request, 'TechnicalCourses/detail.html', {
            # 'parameter':variable
            'course':course,
    })
    '''
    #return HttpResponse('<h2>These are the course details</h2>')
    try:
        course = Allcourses.objects.get(pk=course_id)
    except Allcourses.DoesNotExist:
        raise Http404("Course Not Available")
    return render(request, 'TechnicalCourses/detail.html',{'course':course})
    '''


def yourchoice(request, course_id):
    # get_object_or_404 is a method
    course=get_object_or_404(Allcourses, pk=course_id)
    # use try except in case a course type DNE
    try:
        selected_ct=course.details_set.get(pk=request.POST['choice'])
    except (KeyError, Allcourses.DoesNotExist):
        return render(request, 'TechnicalCourses/detail.html',{
            'course':course,
            'error_message':"Select a valid option, dumbass",
        })
    else:
        selected_ct.your_choice=True
        selected_ct.save()
        return render(request, 'TechnicalCourses/detail.html', {
            'course':course
        })

Website/TechnicalCourses/templates/TechnicalCourses/Courses.html
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<!-- Nav bar using .nav (nav-tabs>Fill and Justify)-->
<nav class="nav nav-pills nav-fill">
  <a class="nav-link active" aria-current="page" href="#">Home</a>
  <a class="nav-link" href="#">Edureka Community</a>
  <a class="nav-link" href="#">Contact</a>
  <!--<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
</nav>
<!-- #ol =ordered list -->
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.CxH5oJPU7bXn5pwnRlfyJAHaDi%26pid%3DApi&f=1"
<h1>Welcome to Edureka!</h1>
<ol>
    <!-- whenever we include python code within html, we do so insider-->
    {% for x in ac %}
    <li><a href="/{{x.id}}/">{{x.coursename}}</a></li>
    {% endfor %}
</ol>

Website/TechnicalCourses/templates/TechnicalCourses/detail.html
{% if course.pk is 1 %}
<img src = https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/180px-Python.svg.png>
<h2>Welcome to the {{course.coursename}} course page led by {{course.insname}}</h2>
<h3>Find the course <a href="https://www.edureka.co/python-scripting">here.</a></h3>
<!--This is an unordered list that contains the self-paced and instructor led options-->
<ul>
    {% for j in Allcourses.set.all %}
    <li>
        {{ j.ct }}
    </li>
    {% endfor %}
</ul>
{% elif course.pk is 2 %}
<h2>Welcome to the {{course.coursename}} course page led by {{course.insname}}</h2>
<h3>Find the course <a href="https://www.edureka.co/java-course-self-paced">here.</a></h3>
{% else %}
<h2>Welcome to the {{course.coursename}} course page led by {{course.insname}}</h2>
<h3>Go find the link yourself, you lazy fuck</h3>
{% endif %}

{% if error_message %}<p><strong>{{error_message}}</strong></p>
{% endif %}

<!--TechnicalCourses used as it is the name of the app-->
<!--This name will be used as the namespace for all the url's present in this app-->
<form action="{% url 'TechnicalCourses:yourchoice' course.id %}"
    method="post">
    <!--post method alters the data on the server side -->
    <!--csrf_token template tag should be used in all post to protect against request forgeries-->
    <!--all post forms targeted at internal urls should use the cross-site request forgeries tag-->
    {% csrf_token %}
    {% for choice in course.details_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{choice.id}">
    <label for="choice{{ forloop.counter }}">{{choice.ct}}</label><br>
    {% endfor %}
    <input type="submit" value="Submit">
</form>